apiVersion: apps/v1
kind: Deployment
metadata:
  name: njs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: njsapp
          image: ajyke/nodejs
          ports:
            - containerPort: 9981
---
apiVersion: v1
kind: Service
metadata:
  name: njssvc
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9981
      nodePort: 31000

